name: Sync NPM Metadata

on:
  release:
    types: [published]

jobs:
  sync-npm-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Fetch NPM Package Metadata
        id: fetch_metadata
        run: |
          PACKAGE_NAME=$(jq -r .name package.json)
          curl -s https://registry.npmjs.org/$PACKAGE_NAME > npm-metadata.json
          echo "Fetched metadata for $PACKAGE_NAME"

      - name: Update README with NPM Version
        run: |
          NPM_VERSION=$(jq -r .version npm-metadata.json)
          sed -i "s/^Version: .*/Version: $NPM_VERSION/" README.md
          echo "Updated README with version $NPM_VERSION"

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: sync README with npm version $NPM_VERSION"
          git push
